spring.application.name=hbmarathon

spring.datasource.url=jdbc:postgresql://localhost:5432/hbmarathon_db
spring.datasource.username=hbmarathon_user
spring.datasource.password=hbmarathon_pass
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

